name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      # you could use this action to install and update miktex
      - uses: CatInCosmicSpace/latex-template/actions/miktex@master
      # this lines compiles pdf
      - name: Compile example
        run: |
          latexmk -pdf -xelatex main.tex
          latexmk -pdf -xelatex main-en.tex
      - name: Clean after build example
        run: |
          latexmk -c ./main.tex
          latexmk -c ./main-en.tex
      # and this lines published artifacts to github actions
      - name: "Git artifact: PDF"
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: |
            ./main.pdf
            ./main-en.pdf

